import { SectionHeader } from "./section-header";
import { Info } from "lucide-react";

export function MetadataPanel() {
  const metadata = [
    { label: "Analyst", value: "LegalAI-v1" },
    { label: "Last Updated", value: "2024-05-20" },
    { label: "Documents", value: "12 files" },
    { label: "Status", value: "Final Review" },
  ];

  return (
    <div className="space-y-4">
      <SectionHeader title="Analysis Metadata" />
      <div className="rounded-lg border bg-muted/30 p-3 space-y-3">
        {metadata.map((item) => (
          <div key={item.label} className="flex justify-between items-center">
            <span className="text-xs text-muted-foreground">{item.label}</span>
            <span className="text-xs font-medium">{item.value}</span>
          </div>
        ))}
      </div>
      <div className="flex items-start gap-2 p-3 rounded-lg bg-blue-50 dark:bg-blue-900/20 text-blue-800 dark:text-blue-300 border border-blue-100 dark:border-blue-800">
        <Info className="h-4 w-4 shrink-0 mt-0.5" />
        <p className="text-[10px] leading-relaxed">
          This analysis was generated by our AI models and should be verified by a legal professional.
        </p>
      </div>
    </div>
  );
}
