# -*- coding: utf-8 -*-
"""4_algorithm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H759mQEwpHwxtL7thtjMw_K-fIbmB-OP
"""

# Install required libraries in Colab

# Verify GPU availability
import torch
print("GPU Available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("Device Name:", torch.cuda.get_device_name(0))

import json
import spacy

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader


from torchcrf import CRF

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

idx2tag = {v: k for k, v in tag2idx.items()}

# PyTorch Dataset Definition
class LegalNERDataset(Dataset):
    def __init__(self, sentences, tags, word2idx, tag2idx, max_len=128):
        self.sentences = sentences
        self.tags = tags
        self.word2idx = word2idx
        self.tag2idx = tag2idx
        self.max_len = max_len

    def __len__(self):
        return len(self.sentences)

    def __getitem__(self, idx):
        seq = self.sentences[idx]
        tag_seq = self.tags[idx]

        x = [self.word2idx.get(w, self.word2idx.get("UNK", 1)) for w in seq]
        y = [self.tag2idx.get(t, self.tag2idx.get("O", 0)) for t in tag_seq]

        x = x[:self.max_len] + [self.word2idx.get("PAD", 0)] * max(0, self.max_len - len(x))
        y = y[:self.max_len] + [self.tag2idx.get("PAD", 0)] * max(0, self.max_len - len(y))

        return torch.tensor(x, dtype=torch.long), torch.tensor(y, dtype=torch.long)

# BiLSTM-CRF Model Architecture
class BiLSTM_CRF(nn.Module):
    def __init__(self, vocab_size, tag_to_ix, embedding_dim=128, hidden_dim=256):
        super(BiLSTM_CRF, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim, padding_idx=0)
        self.lstm = nn.LSTM(embedding_dim, hidden_dim // 2, num_layers=1, bidirectional=True, batch_first=True)
        self.hidden2tag = nn.Linear(hidden_dim, len(tag_to_ix))
        self.crf = CRF(len(tag_to_ix), batch_first=True)

    def forward(self, x):
        embeds = self.embedding(x)
        lstm_out, _ = self.lstm(embeds)
        return self.hidden2tag(lstm_out)

    def loss(self, x, tags, mask):
        emissions = self.forward(x)
        return -self.crf(emissions, tags, mask=mask, reduction='mean')

    def predict(self, x, mask):
        emissions = self.forward(x)
        return self.crf.decode(emissions, mask=mask)


import pandas as pd
import xgboost as xgb
from sklearn.metrics import accuracy_score, classification_report

import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments
from datasets import Dataset

# 1. Load Pre-trained LegalBERT
model_name = "nlpaueb/legal-bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=3) # 0: Entailment, 1: Neutral, 2: Contradiction

import torch
import torch.nn.functional as F
from torch_geometric.nn import RGCNConv
from torch_geometric.data import Data


# 2. Define R-GCN Architecture
class LegalRGCN(torch.nn.Module):
    def __init__(self, in_channels, hidden_channels, out_channels, num_relations):
        super(LegalRGCN, self).__init__()
        self.conv1 = RGCNConv(in_channels, hidden_channels, num_relations=num_relations)
        self.conv2 = RGCNConv(hidden_channels, out_channels, num_relations=num_relations)

    def forward(self, x, edge_index, edge_type):
        x = self.conv1(x, edge_index, edge_type)
        x = F.relu(x)
        x = self.conv2(x, edge_index, edge_type)
        return x

# 3. Model Initialization & Forward Pass
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
rgcn_model = LegalRGCN(in_channels=8, hidden_channels=16, out_channels=2, num_relations=3).to(device)

